shandyNews/shandyNews/urls.py
from django.conf.urls import include, url
from django.contrib import admin
# from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required as auth
# from links.views import LinkListView, UserProfileDetailView, UserProfileEditView, LinkeCreateView
import links.views as lviews

urlpatterns = [
    url(r'^$', lviews.LinkListView.as_view(), name='home'),
    # url(r'^login/$', auth_views.LoginView.as_view(), {
    #     'template_name': 'templates/login.html'}, name="login"),
    # url(r'^logout/$', auth_views.LogoutView.as_view(),
    #     name="logout"),
    # url(r'^login/$', auth_views.login, name='login'),
    # url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^users/(?P<slug>\w+)/$', lviews.UserProfileDetailView.as_view(), name="profile"),
    url(r'^edit_profile/$', auth(lviews.UserProfileEditView.as_view()), name="edit_profile"),
    url(r'^link/create/$', auth(lviews.LinkeCreateView.as_view()), name='link_create'),
    url(r'^link/(?P<pk>\d+)/$', lviews.LinkDetailView.as_view(),
        name='link_detail'),
    url(r'^link/update/(?P<pk>\d+)/$', auth(lviews.LinkUpdateView.as_view()),
        name='link_update'),
    url(r'^link/delete/(?P<pk>\d+)/$', auth(lviews.LinkDeleteView.as_view()),
        name='link_delete'),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^vote/$', auth(lviews.VoteFormView.as_view()), name="vote")
]

shandyNews/links/models.py
from django.db import models
from django.db.models import Count
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.utils.timezone import now

# Create your models here.

class Link(models.Model):
    title = models.CharField("Headline", max_length=100)
    submitter = models.ForeignKey(User)
    submitted_on = models.DateTimeField(auto_now_add=True)
    rank_score = models.FloatField(default=0.0)
    url = models.URLField("URL", max_length=250, blank=True)
    description = models.TextField(blank=True)

    objects = models.Manager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("link_detail", kwargs={"pk": str(self.id)})

    def set_rank(self, votes):
        # Based on HN ranking algo at http://amix.dk/blog/post/19574
        SECS_IN_HOUR = float(60*60)
        GRAVITY = 1.2

        delta = now() - self.submitted_on
        item_hour_age = delta.total_seconds() // SECS_IN_HOUR
        votes = self.votes - 1
        self.rank_score = votes / pow((item_hour_age+2), GRAVITY)
        self.save()


class Vote(models.Model):
    voter = models.ForeignKey(User)
    link = models.ForeignKey(Link)

    def __str__(self):
        return "%s upvoted %s" % (self.voter.username, self.link.title)

class UserProfile(models.Model):
    user = models.OneToOneField(User, unique=True)
    bio = models.TextField(null=True)

    def __unicode__(self):
        return "%s's profile" % self.user

def create_profile(sender, instance, created, **kwargs):
    if created:
        profile, created = UserProfile.objects.get_or_create(user=instance)


# Signal while saving user
from django.db.models.signals import post_save
post_save.connect(create_profile, sender=User)

shandyNews/links/forms.py
from django import forms
from .models import UserProfile, Link, Vote

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ('user',)

class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        exclude = ("submitter", "rank_score",)

class VoteForm(forms.ModelForm):
    class Meta:
        model = Vote
        exclude = ('voter', 'link')

shandyNews/links/views.py
import json

from django.db.models import Count
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.views.generic.edit import UpdateView, CreateView, DeleteView, FormView
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse, reverse_lazy
from django_comments.models import Comment
from django.http import HttpResponse

from .models import Link, Vote, UserProfile
from .forms import UserProfileForm, LinkForm, VoteForm

# Create your views here.

class RandomGossipMixin(object):
    def get_context_data(self, **kwargs):
        context = super(RandomGossipMixin, self).get_context_data(**kwargs)
        context[u"randomquip"] = Comment.objects.order_by('?')[0]
        return context


class LinkListView(RandomGossipMixin, generic.ListView):
    model = Link
    template_name = 'links/link_list.html'
    # queryset = Link.with_votes.all()
    queryset = Link.objects.annotate(votes=Count('vote')).order_by('-votes')
    paginate_by = 10


    def get_context_data(self, **kwargs):
        context = super(LinkListView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            voted = Vote.objects.filter(voter=self.request.user)
            links_in_page = [link.id for link in context["object_list"]]
            voted = voted.filter(link_id__in=links_in_page)
            voted = voted.values_list('link_id', flat=True)
            context["voted"] = voted
        return context

class UserProfileDetailView(generic.DetailView):
    model = get_user_model()
    slug_field = "username"
    template_name = "user_detail.html"

    def get_object(self, queryset=None):
        user = super(UserProfileDetailView, self).get_object(queryset)
        UserProfile.objects.get_or_create(user=user)
        return user

class UserProfileEditView(UpdateView):
    model = UserProfile
    form_class = UserProfileForm
    template_name = "edit_profile.html"

    def get_object(self, queryset=None):
        return UserProfile.objects.get_or_create(user=self.request.user)[0]

    def get_success_url(self):
        return reverse("profile", kwargs={'slug': self.request.user})

class LinkeCreateView(CreateView):
    model = Link
    form_class = LinkForm

    def form_valid(self, form):
        f = form.save(commit=False)
        f.rank_score = 0.0
        f.submitter = self.request.user
        f.save()

        return super(CreateView, self).form_valid(form)

class LinkDetailView(generic.DetailView):
    model = Link

class LinkUpdateView(UpdateView):
    model = Link
    form_class = LinkForm

class LinkDeleteView(DeleteView):
    model = Link
    success_url = reverse_lazy("home")

class JSONFormMixin(object):
    def create_response(self, vdict=dict(), valid_form=True):
        response = HttpResponse(json.dumps(vdict), content_type='application/json')
        response.status = 200 if valid_form else 500
        return response

class VoteFormBaseView(FormView):
    form_class = VoteForm

    def create_response(self, vdict=dict(), valid_form=True):
        response = HttpResponse(json.dumps(vdict))
        response.status = 200 if valid_form else 500
        return response

    def form_valid(self, form):
        link = get_object_or_404(Link, pk=form.data["link"])
        user = self.request.user
        prev_votes = Vote.objects.filter(voter=user, link=link)
        has_voted = (len(prev_votes) > 0)

        ret = {"success": 1}
        if not has_voted:
            # add vote
            v = Vote.objects.create(voter=user, link=link)
            ret["voteobj"] = v.id
        else:
            # delete vote
            prev_votes[0].delete()
            ret["unvoted"] = 1
        return self.create_response(ret, True)

    def form_invalid(self, form):
        ret = {"success": 0, "form_errors": form.errors }
        return self.create_response(ret, False)

class VoteFormView(JSONFormMixin, VoteFormBaseView):
    pass

shandyNews/links/templates/edit_profile.html
{% extends "base.html" %}

{% block content %}
<h2>{{ user.username }}'s Profile</h2>

<form method="post" action="">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Edit">
</form>

{% endblock %}

shandyNews/links/templates/links/comments.html
{% extends "base.html" %}

{% block content %}
{% load mptt_tags %}
<ul>
    {% recursetree nodes %}
        <li>
            {{ node.name }}
            {% if not node.is_leaf_node %}
                <ul class="children">
                    {{ children }}
                </ul>
            {% endif %}
        </li>
    {% endrecursetree %}
</ul>
{% endblock %}

shandyNews/links/templates/links/link_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<p>Are you sure you want to delete "{{ object.title }}"?</p>

<form method="post" action="{% url 'link_delete' pk=object.pk %}">
  {% csrf_token %}
  <a href="{% url 'link_detail' pk=object.pk %}">Go back</a>
  <p><input type="submit" value="Confirm deletion" /></p>
</form>

{% endblock %}

shandyNews/links/templates/links/link_detail.html
{% extends "base.html" %}
{% load comments %}

{% block content %}
<style>
  #id_honeypot {
    display: none;
  }
</style>

<h2><a href="{{ object.link }}">{{ object.title }}</a></h2>
{% if object.submitter == user %}
  <a href="{% url 'link_update' pk=object.pk %}">Edit</a> |
  <a href="{% url 'link_delete' pk=object.pk %}">Delete</a>
{% endif %}

<div class="desc">
  {{ object.description }}
</div>

<div class="comments">
  <h3>Comments</h3>

  <div class="comment_form">
{% if user.is_authenticated %}
  {% get_comment_form for object as form %}
  <form action="{% comment_form_target %}" method="POST">
    {% csrf_token %}
    {{ form.comment }}
    {{ form.honeypot }}
    {{ form.content_type }}
    {{ form.object_pk }}
    {{ form.timestamp }}
    {{ form.security_hash }}
    <input type="hidden" name="name" value="{{ user }}" />
    <input type="hidden" name="email" value="{{ user.email|default:'d@ummy.com' }}" />
    <input type="hidden" name="url" value="" />
    <input type="hidden" name="next"
	   value="{% url 'link_detail' pk=object.id %}" />
    <input type="submit" value="Add comment" id="id_submit" />
  </form>
{% else %}
  <p>Please <a href="{% url 'login' %}">log in
  </a> to leave a comment.</p>
{% endif %}
  </div>


  {% render_comment_list for object %}
</div>


{% endblock %}

shandyNews/links/templates/links/link_form.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Add">
</form>
{% endblock %}

shandyNews/links/templates/links/link_list.html
{% extends "base.html" %}
{% load comments %}
{% block content %}

{% if is_paginated %}
<ol start="{{ page_obj.start_index }}">
{% else %}
<ol>
{% endif %}

{% for link in object_list %}
  <form method="post" action="{% url 'vote' %}" class="vote_form">
    <li> [{{ link.votes }}]
    {% csrf_token %}
    <input type="hidden" id="id_link" name="link" class="hidden_id" value="{{ link.pk }}" />
    <input type="hidden" id="id_voter" name="voter" class="hidden_id" value="{{ user.pk }}" />
    {% if not user.is_authenticated %}
    <button disabled title="Please login to vote">+</button>
    {% elif link.pk not in voted %}
    <button>+</button>
    {% else %}
    <button>-</button>
    {% endif %}
    <a href="{% url 'link_detail' pk=link.pk %}">
      <b>{{ link.title }}</b>
      {% get_comment_count for link as comment_count %}
      {{ comment_count }} comment{{ comment_count|pluralize }}
    </a>
    </li>
  </form>
{% endfor %}
</ol>

{% if is_paginated %}
<div class="pagination">
  {% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}">More &raquo;</a>
  {% endif %}
</div>
{% endif %}



<blockquote style="background-color: #ddd; padding: 4px; border-radius: 10px; margin: 10px 0; color: #666; font-size: smaller; text-shadow: rgba(255,255,255,0.8) 1px 1px 0;">
{{ randomquip.comment|truncatechars:140 }}
</blockquote>

{% endblock %}

shandyNews/links/templates/user_detail.html
{% extends "base.html" %}

{% block content %}
<h2>{{ object.username }}'s Profile</h2>
{% if object.userprofile.bio %}
<div>
<b>Bio:</b>
{{ object.userprofile.bio }}
</div>
{% endif %}
{% if object.username == request.user.username %}
<p><a href='{% url "edit_profile" %}'>Edit my profile</a></p>
{% endif %}

{% endblock %}

shandyNews/shandyNews/templates/sitebase.html
{% extends "base.html" %}

{% load static %}

<html>
<head>
  <title>Shandy News</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
</head>
<body>
<h1>Shandy News</h1>

{% block content %}
{% endblock %}

<footer>
  <p>
    <a href="{% url 'home' %}">Home</a> |
{% if user.is_authenticated %}
    <a href="{% url 'logout' %}">Logout</a> |
{% else %}
    <a href="{% url 'login' %}">Login</a>
{% endif %}
  </p>
</footer>
</body>
</html>

shandyNews/templates/base.html
{% extends "base.html" %}

{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>{% block head_title %}Shandy News{% endblock %}</title>
    {% block extra_head %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/vote.js' %}"></script>
    {% endblock %}
  </head>
  <body>
    {% block body %}
    <h1>Shandy News</h1>

    {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
	{% for message in messages %}
	<li>{{message}}</li>
	{% endfor %}
      </ul>
    </div>
    {% endif %}

    <div>
      <strong>Menu:</strong>
      <ul>
	{% if user.is_authenticated %}
  <li><a href="{% url 'link_create' %}">Submit Link</a></li>
  <li><a href="{% url 'account_email' %}">Change E-mail</a></li>
	<li><a href="{% url 'account_logout' %}">Sign Out</a></li>
	{% else %}
	<li><a href="{% url 'account_login' %}">Sign In</a></li>
	<li><a href="{% url 'account_signup' %}">Sign Up</a></li>
	{% endif %}
      </ul>
    </div>
    {% block content %}
    {% endblock %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}
  </body>
</html>